server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: syncsenta-ai-service
  profiles:
    active: testnet

# Hedera Testnet Configuration
hedera:
  ai:
    # Hedera Testnet Moonscape AI endpoint
    base-url: ${HEDERA_AI_BASE_URL:https://api.testnet.moonscape.hedera.com/v1}
    # Your Hedera testnet API key - set via environment variable
    api-key: ${HEDERA_AI_API_KEY}
    timeout: 30s
    max-tokens: 1000
    temperature: 0.7
  # Hedera network configuration
  network:
    type: ${HEDERA_NETWORK:testnet}
    node-url: ${HEDERA_NODE_URL:https://testnet.mirrornode.hedera.com}
  # Account configuration for testnet
  account:
    id: ${HEDERA_ACCOUNT_ID}
    private-key: ${HEDERA_PRIVATE_KEY}

# CORS Configuration for React frontend
cors:
  allowed-origins: 
    - http://localhost:5173
    - http://localhost:3000
    - https://syncsenta.netlify.app
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# Logging Configuration
logging:
  level:
    com.syncsenta.ai: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: ALWAYS

---
# Testnet Profile (Default for development)
spring:
  config:
    activate:
      on-profile: testnet

hedera:
  ai:
    base-url: https://api.testnet.moonscape.hedera.com/v1
  network:
    type: testnet
    node-url: https://testnet.mirrornode.hedera.com

logging:
  level:
    com.syncsenta.ai: DEBUG
    org.springframework.web: INFO

---
# Development Profile
spring:
  config:
    activate:
      on-profile: development
  
logging:
  level:
    com.syncsenta.ai: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: production

logging:
  level:
    com.syncsenta.ai: WARN
    org.springframework.web: WARN
