server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: syncsenta-ai-service
  profiles:
    active: development

# Hedera Moonscape AI Configuration
hedera:
  ai:
    base-url: ${HEDERA_AI_BASE_URL:https://api.moonscape.hedera.com/v1}
    api-key: ${HEDERA_AI_API_KEY:your_hedera_ai_api_key_here}
    timeout: 30s
    max-tokens: 1000
    temperature: 0.7

# CORS Configuration for React frontend
cors:
  allowed-origins: 
    - http://localhost:5173
    - http://localhost:3000
    - https://syncsenta.netlify.app
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# Logging Configuration
logging:
  level:
    com.syncsenta.ai: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: ALWAYS

---
# Development Profile
spring:
  config:
    activate:
      on-profile: development
  
logging:
  level:
    com.syncsenta.ai: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: production

logging:
  level:
    com.syncsenta.ai: WARN
    org.springframework.web: WARN
